### PR TITLE
Xo upgrade - attempt #2

### PR DESCRIPTION
**Pull request by whyboris**
- No lint errors
- Unit tests pass
- Up-to-date `xo` module
- Remove node 6 add node 12 in _Travis CI_

🚀 🤞 

Branch based off #28 
Closes the first attepmt #29

### CODE REVIEW

**Comment by whyboris** [comment]
Unsure what happened with the _git_ history 🤷‍♂ 
But this may fix the problem: https://github.com/KhaledMohamedP/translate-json-object/pull/29#issuecomment-560351837

**Comment by KhaledMohamedP** [comment]
Unfortunately, I am seen the error in both PRs!

Screen Shot 2019-12-09 at 11 00 03 PM

**Comment by whyboris** [comment]
Very odd -- I'll try to figure something out 🤷‍♂

**Comment by KhaledMohamedP** [comment]
Thanks for trying here @whyboris 🙏

**Pull request closed without merging**
