### PR TITLE
xo upgrade & fix lint errors

### PR DESCRIPTION
**Pull request by whyboris**
- No lint errors
- Unit tests pass
- Up-to-date `xo` module
- Remove node 6 add node 12 in _Travis CI_

🚀 🤞 

Branch based off #28

### CODE REVIEW

**Comment by whyboris** [comment]
CI build failed because _Node 6_ can't handle `async ()`
I advise to remove support for _Node 6_ as it's deprecated: [Node Releases](https://nodejs.org/en/about/releases/)

**Comment by KhaledMohamedP** [comment]
Looks like there is a merge conflict, can you fix it?

**Comment by whyboris** [comment]
Sorry unsure where. All I see at the bottom of this PR is this:

image

**Comment by KhaledMohamedP** [comment]
I am seeing a different message which blocks me from merging this PR. Try rebasing from `origin/master` and resolve any conflicts and push again.

**Comment by whyboris** [comment]
I opened #30 -- everything I tried with _git_ told me that the `xo-upgrade` branch was up to date with `origin/master` 🤷‍♂

**Pull request closed without merging**
